version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.4
    command: 
      - "--api.insecure=true" 
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.docker.network=pred-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - pred-network
  model_service:
    image: x86_64/cassava-model-service:0.8.1
    container_name: model_service
    networks:
      - simp-network
    environment:
      MODEL_NAME: saved_model
    networks:
      - pred-network
  model_api:
    image: x86_64/cassava-prediction-service:0.8.1
    container_name: model_api
    environment:
      SERVING_SERVICE: model_service
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.model_api.rule=Host(`model_api.localhost`)
    networks:
      - pred-network
  model_ui:
    image: x86_64/cassava-prediction-ui:0.8.1
    container_name: model_ui
    expose:
      - 80
      - 443
    labels:
      - traefik.enable=true
      - traefik.http.routers.model_ui.rule=Host(`model_ui.localhost`)
    networks:
      - pred-network
networks:
  pred-network:
